name: Enforce Commit Email
on:
  push:
    branches:
      - main
      - develop

jobs:
  validate-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit author email
        run: |
          ALLOWED_EMAIL="admin@pgelephant.com"
          echo "Validating commits..."
          git fetch origin $GITHUB_REF --depth=20
          for commit in $(git rev-list origin/$GITHUB_REF..HEAD); do
            AUTHOR_EMAIL=$(git show -s --format='%ae' "$commit")
            if [ "$AUTHOR_EMAIL" != "$ALLOWED_EMAIL" ]; then
              echo "❌ Commit $commit uses disallowed email: $AUTHOR_EMAIL"
              exit 1
            fi
          done
          echo "✅ All commits from allowed email."

