name: pgbalancer Release

# Only run manually for releases
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      release_type:
        description: 'Type of release'
        required: true
        default: 'minor'
        type: choice
        options:
        - patch
        - minor
        - major
        - prerelease
      create_tag:
        description: 'Create Git tag'
        required: true
        default: true
        type: boolean
      publish_docker:
        description: 'Publish Docker images'
        required: false
        default: true
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  validate-release:
    name: Validate Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Validate version format
      run: |
        VERSION="${{ github.event.inputs.version }}"
        if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\-\.]+)?$ ]]; then
          echo "Invalid version format: $VERSION"
          echo "Expected format: v1.0.0 or v1.0.0-beta.1"
          exit 1
        fi
        echo "Version format is valid: $VERSION"
        
    - name: Check if tag already exists
      run: |
        VERSION="${{ github.event.inputs.version }}"
        if git tag -l | grep -q "^$VERSION$"; then
          echo "Tag $VERSION already exists"
          exit 1
        fi
        echo "Tag $VERSION does not exist"

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    needs: validate-release
    
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autotools-dev \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libjson-c-dev \
          libyaml-dev \
          libpq-dev \
          libssl-dev \
          libpam0g-dev \
          libldap2-dev \
          gcc-aarch64-linux-gnu
        
    - name: Setup PostgreSQL 16
      run: |
        sudo apt-get install -y postgresql-16 postgresql-16-dev
        
    - name: Configure build
      run: |
        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
        fi
        ./configure --with-openssl --with-pam --with-ldap
        
    - name: Build release
      run: |
        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
        fi
        make -C bin/bctl
        make -C src
        
    - name: Create release archive
      run: |
        VERSION="${{ github.event.inputs.version }}"
        TARGET="${{ matrix.target }}"
        
        mkdir -p release
        cp bin/bctl/bctl release/bctl-$VERSION-$TARGET
        cp src/pgbalancer release/pgbalancer-$VERSION-$TARGET || echo "pgbalancer binary not found, skipping"
        
        # Create documentation archive
        cp -r docs release/docs-$VERSION
        
        # Create complete release archive
        tar -czf pgbalancer-$VERSION-$TARGET.tar.gz -C release \
          bctl-$VERSION-$TARGET \
          pgbalancer-$VERSION-$TARGET \
          docs-$VERSION
        
        # Create binary-only archive
        tar -czf pgbalancer-binaries-$VERSION-$TARGET.tar.gz -C release \
          bctl-$VERSION-$TARGET \
          pgbalancer-$VERSION-$TARGET
        
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pgbalancer-${{ github.event.inputs.version }}-${{ matrix.target }}
        path: |
          pgbalancer-${{ github.event.inputs.version }}-${{ matrix.target }}.tar.gz
          pgbalancer-binaries-${{ github.event.inputs.version }}-${{ matrix.target }}.tar.gz
        retention-days: 90

  create-tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    needs: [validate-release, build-release]
    if: ${{ github.event.inputs.create_tag == 'true' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Create and push tag
      run: |
        VERSION="${{ github.event.inputs.version }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "$VERSION" -m "Release $VERSION"
        git push origin "$VERSION"
        echo "Created and pushed tag: $VERSION"

  publish-docker:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: [validate-release, build-release]
    if: ${{ github.event.inputs.publish_docker == 'true' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: pgelephant/pgbalancer
        tags: |
          type=raw,value=${{ github.event.inputs.version }}
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pgelephant/pgbalancer
        short-description: "pgbalancer - Modern PostgreSQL connection pooler with REST API"

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [create-tag, publish-docker]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: pgbalancer ${{ github.event.inputs.version }}
        body: |
          ## pgbalancer ${{ github.event.inputs.version }}
          
          **Release Type:** ${{ github.event.inputs.release_type }}
          
          ### What's New
          - Modern REST API management interface
          - Professional CLI tool (bctl)
          - YAML configuration support
          - PostgreSQL 13-18 compatibility
          - High availability features
          - Connection pooling and load balancing
          
          ### Installation
          
          **Docker:**
          ```bash
          docker pull pgelephant/pgbalancer:${{ github.event.inputs.version }}
          ```
          
          **Binary:**
          Download the appropriate binary for your platform from the assets below.
          
          ### Documentation
          - [Installation Guide](https://pgelephant.github.io/pgbalancer/getting-started/installation/)
          - [Quick Start](https://pgelephant.github.io/pgbalancer/getting-started/quick-start/)
          - [API Reference](https://pgelephant.github.io/pgbalancer/api/)
          
          ---
          
          **Triggered by:** @${{ github.actor }}
          **Release Type:** ${{ github.event.inputs.release_type }}
        files: ./artifacts/*
        draft: false
        prerelease: ${{ github.event.inputs.release_type == 'prerelease' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-completion:
    name: Notify Release Completion
    runs-on: ubuntu-latest
    needs: [create-github-release]
    if: always()
    
    steps:
    - name: Release Summary
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "pgbalancer Release $VERSION completed!"
        echo ""
        echo "Release Summary:"
        echo "  Version: $VERSION"
        echo "  Type: ${{ github.event.inputs.release_type }}"
        echo "  Tag Created: ${{ github.event.inputs.create_tag }}"
        echo "  Docker Published: ${{ github.event.inputs.publish_docker }}"
        echo ""
        echo "Links:"
        echo "  GitHub Release: https://github.com/pgelephant/pgbalancer/releases/tag/$VERSION"
        echo "  Docker Hub: https://hub.docker.com/r/pgelephant/pgbalancer"
        echo ""
        echo "All release tasks completed successfully!"
